manifest:
  remotes:
    - name: zephyrporject-rtos
      url-base: https://github.com/zephyrproject-rtos
  projects:
    - name: zephyr
      remote: zephyrporject-rtos
      revision: d92b199173d7cce41f4837cffa93637fe50dfcf2
      import: true
  self:
    path: application
